# Generated by Django 5.0.3 on 2024-03-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisees', '0006_remove_advisee_advisor'),
        ('advisors', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectArea',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='subject',
        ),
        migrations.AddField(
            model_name='advisor',
            name='subjects',
            field=models.ManyToManyField(to='advisees.subjectarea'),
        ),
    ]
