# Generated by Django 5.0.3 on 2024-03-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0005_delete_subjectarea_remove_advisor_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='is_advisor',
            field=models.BooleanField(default=True),
        ),
    ]
