# Generated by Django 5.0.3 on 2024-03-24 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisees', '0003_delete_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisee',
            name='subject_needed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advisees.subjectarea'),
        ),
    ]
