# Generated by Django 5.0.3 on 2024-03-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisees', '0005_advisee_advisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisee',
            name='advisor',
        ),
    ]
